from codingdojo/engineeringdojo:junghans_engineeringdojo

ARG TRAVIS
ARG TRAVIS_PULL_REQUEST
ARG TRAVIS_REPO_SLUG
ARG TRAVIS_BRANCH
ARG TRAVIS_COMMIT

RUN dnf install -y -q make git gcc-c++ pkgconfig

USER dojo
WORKDIR /tmp
RUN git clone --recursive https://github.com/${TRAVIS_REPO_SLUG} docker-test
WORKDIR docker-test

RUN if [ ${TRAVIS} = true ]; then \
      if [ ${TRAVIS_PULL_REQUEST} != false ]; then \
        git fetch "git://github.com/${TRAVIS_REPO_SLUG}" +refs/pull/"${TRAVIS_PULL_REQUEST}"/merge: ;\
        git checkout FETCH_HEAD; \
      else \
        git fetch --depth=10 "git://github.com/${TRAVIS_REPO_SLUG}" "${TRAVIS_BRANCH}"; \
        git checkout "${TRAVIS_COMMIT}"; \
      fi \
    fi
RUN make
